#roles:
#  # https://github.com/cloudalchemy/ansible-node-exporter
#  - cloudalchemy.node_exporter,2.0.0
#  # https://github.com/patrickjahns/ansible-role-promtail
#  - patrickjahns.promtail,1.13.1

collections:
  - ansible.netcommon
  - community.crypto
  - community.docker
  - community.general


